secret:
  mongodb_uri: "bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQGRlbW8tZ3Vlc3Rib29rLWRhdGFiYXNlOjI3MDE3L2d1ZXN0Ym9vaz9hdXRoU291cmNlPWFkbWlu"
#              "mongodb://admin:password@demo-guestbook-database:27017/guestbook?authSource=admin"
image:
  repository: phico/backend
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: backend-twinkies.apps-crc.testing
