config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend-twinkies.apps-crc.testing/guestbook"
image:
  repository: phico/frontend
  tag: "2.0"
  pullPolicy: Always
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: frontend-twinkies.apps-crc.testing